### ISSUE TITLE
Build fails on CentOS-7

### ISSUE THREAD

**Issue by daniel-sherwood** [AArnott/Nerdbank.GitVersioning#208] opened 2018-08-15 09:45 UTC
Hi

I have this working under Windows, but it fails under CentOS-7 with the following error.

`/home/vagrant/.nuget/packages/nerdbank.gitversioning/2.1.65/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library '/home/vagrant/.nuget/packages/nerdbank.gitversioning/2.1.65/build/MSBuildFull/lib/linux/x86_64/libgit2-1196807.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libssl.so.1.0.0: cannot open shared object file: No such file or directory [/vagrant/src/NodeHosts/TimeTickerHost/TimeTickerHost.csproj]
`
This appears to be due to the use of libssl-1.0.0 from the builtin libgit.  CentOS7 deprecated libssl in favour of OpenSSL and libssl-1.0.0 is not available.

Cheers

Daniel

**Comment by AArnott** [comment] 2018-08-15 19:53
Dupe of #143

**Closed by AArnott** 2018-08-15 19:53 UTC
