### ISSUE TITLE
Since 2.3.151, package version calculation sometimes off

### ISSUE THREAD

**Issue by qmfrederik** [AArnott/Nerdbank.GitVersioning#408] opened 2019-11-22 13:09 UTC
I have a .NET repository which uses nbgv, and builds with Travis, at https://github.com/qmfrederik/dotnet-packaging.

This repository contains a single solution file and multiple projects. They all share the same `version.json` file.
I expect all projects to end up with the same version number, when built at the same time.

One of the projects writes its version number to a file at compile time.
At a later step, the version number is retrieved and used to add NuGet references to the earlier built packages.

When I upgrade nbgv from 2.3.138 to 2.3.151 (see https://github.com/qmfrederik/dotnet-packaging/pull/126), I noticed that "sometimes" on of the projects has a release version number, instead of a prerelease version number.

https://travis-ci.org/qmfrederik/dotnet-packaging/builds/615538797 shows about half of the builds failing.

If you search the logs for `Successfully created package`, you'll see:

```
Successfully created package '[..]/Packaging.Targets.0.1.104.nupkg'.
Successfully created package '[..]/dotnet-tarball.0.1.104-g7186748eee.nupkg'.
Successfully created package '[..]/dotnet-rpm.0.1.104-g7186748eee.nupkg'.
Successfully created package '[..]/dotnet-deb.0.1.104-g7186748eee.nupkg'.
```

on failing builds, and

```
Successfully created package '[..]/Packaging.Targets.0.1.104-g7186748eee.nupkg'.
Successfully created package '[..]/dotnet-tarball.0.1.104-g7186748eee.nupkg'.
Successfully created package '[..]/dotnet-zip.0.1.104-g7186748eee.nupkg'.
Successfully created package '[..]/dotnet-deb.0.1.104-g7186748eee.nupkg'.
```

on successful builds.

Note that the `-g7186748eee` prefix is missing from `Packaging.Targets` in the failing build.

**Comment by AArnott** [comment] 2019-11-22 16:47
Very curious. The determination of whether we consider this a public release is pretty simple. 

1. We honor the MSBuild `PublicRelease` property if it has already been set
1. Otherwise we calculate it based on version.json's `publicReleaseRefSpec`.

Can you reproduce this when building locally?
Can you capture a repro during a build (either locally or in travis) with the `/bl` switch passed to msbuild or `dotnet build` and salvage the resulting `msbuild.binlog` file and share it out? That will contain the diagnostic msbuild logs (including your env vars) that should help us determine whether the `GetBuildVersion` task in msbuild was invoked with `PublicRelease` preset. You could review the file yourself (using the tool at http://msbuildlog.com) if you'd rather not share it.

**Comment by AArnott** [comment] 2019-12-20 22:27
Closing due to non-response.

**Closed by AArnott** 2019-12-20 22:27 UTC
