### ISSUE TITLE
What is the correct way to set the NuGet version of a set of packages that reference each other

### ISSUE THREAD

**Issue by pshrosbree** [AArnott/Nerdbank.GitVersioning#157] opened 2017-12-13 17:48 UTC
When I use Nerdbank.GitVersioning in my .csproj files, and some projects reference each other, and all have the same version as specified in verison.json, the generated packages reference >= v1.0.0 of the other referenced csproj packages. It is not clear from the documentation how to get them to reference the current version.
I thought that one would be able to add the `<Version>` element in the csproj with some variable as its content. If so, where is that variable documented, and how is its value generated before the Nerdbank.GitVersioning is seen?
If not, how is this achieved?
I can write a script that runs before the build and either sets an environment variable or updates the .csproj files with the correct version, but that seems to make Nerdbank.GitVersioning of limited use.
I imagine this is the normal versioning requirement, so I am sure I am missing some documentation. Any pointers would be appreciated.

**Comment by AArnott** [comment] 2017-12-13 18:48
Great question. It's a dupe of #113 which describes the workaround to the Nuget bug.

**Closed by AArnott** 2017-12-13 18:48 UTC

**Comment by pshrosbree** [comment] 2017-12-13 23:21
I saw #113 but did not like that answer. My workaround is to get the NuGet version string in the Setup method of my Cake build script by invoking the Get-Version.ps1 tool. I then pass that to MSBuild as a property via the 'dotnet' invocations, and have the Version element of the csproj set by that value. It is a five line change to the Cake build script, and does not require messing up the csproj scripts at all.

I should write a Cake addin for this, and submit a PE, and will do so if I ever need this again.

**Comment by pshrosbree** [comment] 2017-12-13 23:22
*PR
