### ISSUE TITLE
Invalid verison string for SemVer 1 in 2.3

### ISSUE THREAD

**Issue by onovotny** [AArnott/Nerdbank.GitVersioning#273] opened 2018-12-14 14:48 UTC
With 2.3, I'm getting errors due to invalid SemVer1 versions on prerelease branches:

```
 "SemVer1": "5.0.119c40d733f04",
  "SemVer2": "5.0.119-c40d733f04",
  "SemVer1NumericIdentifierPadding": 4
```

It's not putting a dot after the height and that causes things to barf when parsing.

I need the SemVer1 for Chocolatey as they don't support SemVer 2 versions yet. And I got a build error without the g due to starting with a number.

**Comment by AArnott** [comment] 2018-12-14 16:18
Oops. I guess we have a missing unit test for this case. 
You mentioned this was on prerelease branches. Did you mean that, or did you mean "non-public release" branches? I don't see any -prerelease suffix in your version.

**Comment by AArnott** [comment] 2018-12-14 16:22
I can repro the problem on a non-public, stable release branch. It shows up for SemVer1, but doesn't show up on `NuGetPackageVersion` which has a good value.

Given chocolatey is based on an older nuget semver 1 system, I think you should be getting your version from `NuGetPackageVersion` rather than `SemVer1`, since as of #269 these two are not the same (since NuGet's semver1 support is actually a *subset* of semver1.

**Comment by onovotny** [comment] 2018-12-14 16:30
I need NuGetPackageVersion to be v2 but still have a v1 compatible one in another variable I can use.

**Comment by AArnott** [comment] 2018-12-14 16:34
OK, so I have a fix for this regression.

Note however, that there may be a lingering issue for you. If chocolatey has the same issue that NuGet semver1 support had (that -prerelease identifiers cannot start with a digit), then the `SemVer1` property will fail for Chocolatey packages whenever the commit starts with a digit. This is because the `SemVer1` property no longer includes the `g` prefix for commit IDs (since semver1 itself doesn't require it, and everyone voted for the change). I retained the `g` in the `NuGetPackageVersion` (when it is in semver v1 mode) to avoid regressing NuGet.

So if your scenario requires both a NuGet-compatible semver v1 value for Chocolatey *and* a semver 2.0 version stamp on your actual NuGet package, NB.GV 2.3 is going to create problems for you unless we somehow fill that gap.

**Comment by AArnott** [comment] 2018-12-14 16:46
Please open a new issue if the above is in fact your situation and you can't upgrade to 2.3

**Closed** 2018-12-14 16:45 UTC
Labels: bug

**Comment by onovotny** [comment] 2018-12-14 16:57
Okay, done: https://github.com/AArnott/Nerdbank.GitVersioning/issues/275
