### ISSUE TITLE
Tasks/Targets version mismatch causes build breaks

### ISSUE THREAD

**Issue by mlr-msft** [AArnott/Nerdbank.GitVersioning#63] opened 2016-05-19 18:05 UTC
We get the following build error intermittently when running a local build and consistently when using VSO's CI support:

```
##[error]packages\Nerdbank.GitVersioning.1.4.19\build\Nerdbank.GitVersioning.targets(40,7): Error MSB4064: The "BuildMetadata" parameter is not supported by the "GetBuildVersion" task. Verify the parameter exists on the task, and it is a settable public instance property.
```

When building locally, the error appears to correlate with cleaning the solution and/or rebuilding, as opposed to simply using incremental builds.

Thanks in advance.

**Comment by AArnott** [comment] 2016-05-20 00:27
This _looks_ like a dupe of #48. But that has long since been fixed for 1.4.19 -- or at least so I thought.
The problem as I understand it tends to manifest when you are using MSBuild to build multiple projects that use distinct versions of Nerdbank.GitVersioning, but a reused MSBuild.exe process across the two builds would use the wrong version of the MSBuild task that had been loaded for another project on the next project, causing errors like this.

"msbuild /nr:false" is a quick fix for this, because it ensures that msbuild.exe nodes are not reused. But I'd like to fix this completely so it's not necessary if I can.

Can you confirm any or all of the following next time it repros:

1. you have been building multiple projects (even across repos) that use different versions of NB.GV
1. at least one of the loaded msbuild.exe processes have some version of NB.GV assemblies loaded that is *not* 1.4.19.

**Comment by AArnott** [comment] 2016-05-20 04:12
I just saw this on my own machine while updating NB.GV from 1.4.6 to 1.4.19. It seems MSBuild won't load multiple versions of the task assembly into a process even if they have unique assembly versions. :(

**Comment by AArnott** [comment] 2016-05-20 04:21
I saw two msbuild.exe processes: one had 1.4.6 loaded and the other had 1.4.19 loaded. Then I'm guessing they each took turns building mismatching projects in the PInvoke solution.

Believed repro steps:

```
# using nuget 3.3.0
git clone https://github.com/AArnott/pinvoke.git
cd pinvoke\src
git checkout 1ff09f040daa1c81958bca8e642cdfa134dd3be4~1
nuget restore 
git checkout 1ff09f040daa1c81958bca8e642cdfa134dd3be4
nuget restore 
msbuild 
```

**Comment by mlr-msft** [comment] 2016-05-20 17:01
Thanks for the prompt response.

We've confirmed that we had a project using an older version of `Nerdbank.GitVersioning` (v 1.3.13) that I was unaware of when I performed the integration work. Eliminating the older version has indeed alleviated the problem in VSO. :smile:

**Comment by AArnott** [comment] 2016-05-20 17:56
Thanks. I'm glad it's alleviated the problem. 
I'm going to keep the issue open at least until I find out if there's anything I can do to make it more resilient to such divergent versions.

**Closed** 2017-06-23 15:16 UTC
