### ISSUE TITLE
Issue with all numeric git commit id starting with 0, and build numbers turned on

### ISSUE THREAD

**Issue by glennawatson** [AArnott/Nerdbank.GitVersioning#350] opened 2019-06-08 08:17 UTC
So I have a bit of a case which wouldn't happen very often in our build server.

We have a all numeric commit id with a leading 0 -- 7.3.5+0566878022

In the NuGet code they have a check for the metadata portion checking which by default in that second section that allow leading 0's is turn to false, and it checks if there is a leading 0 and the commit is all numerics. At the moment you are outputing to the label section, wonder if you should output to the build metadata section?

The below code splits the code into sections, 3 sections are supported, version, labels and build metdata.
 https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Core/NuGet.Versioning/SemanticVersionFactory.cs#L65 

Below is the check for the label section, where it checks for leading 0's and then all numerics.
https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Core/NuGet.Versioning/SemanticVersionFactory.cs#L138

My version.json file is defined as below:

```json
{
  "version": "7.3",
  "publicReleaseRefSpec": [
    "^refs/heads/master$", // we release out of master
    "^refs/heads/develop$", // we release out of develop
    "^refs/heads/rel/\\d+\\.\\d+\\.\\d+" // we also release branches starting with rel/N.N.N
  ],
  "nugetPackageVersion":{
    "semVer": 2
  },
  "cloudBuild": {
    "setVersionVariables": true,
    "buildNumber": {
      "enabled": false
    }
  }
}
```

I'm wondering if maybe it might be a worthwhile change starting to use the pull request value in the `ICloudBuild` interface to add that as a label? If you want me todo the work happy to as well.

Aware this is a bit of a very rare occasion so probably not worth urgent attention.

**Comment by AArnott** [comment] 2019-06-11 08:05
Thanks for reporting.
This looks like a dupe of #302 (at least the way I fixed it).

**Closed by AArnott** 2019-06-11 08:05 UTC

**Comment by glennawatson** [comment] 2019-06-11 08:07
Awesome. Thanks @aarnott see you already got a fix.
