### ISSUE TITLE
dotnet pack produces wrong NuGet version with extra 'g' when set to semVer 2.0

### ISSUE THREAD

**Issue by NightOwl888** [AArnott/Nerdbank.GitVersioning#364] opened 2019-07-02 08:00 UTC
As the title says, `dotnet pack` is producing the wrong version number on the package, even when explicitly passed. I am running on Azure pipelines. 

Here is my configuration for the `feature/foo-bar` branch:

```json
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "1.7-foo-bar.{height}",
  "nuGetPackageVersion": {
    "semVer": 2.0
  },
  "publicReleaseRefSpec": [
    "^refs/heads/master$",
    "^refs/heads/release/v\\d+(?:\\.\\d+)?$"
  ],
  "cloudBuild": {
    "buildNumber": {
      "enabled": true
    }
  },
  "release": {
    "branchName": "release/v{version}"
  }
}
```

Here are the relevant environment variables. See the attachment for the complete log.

```
BUILD_BUILDNUMBER: 1.7.4-foo-bar.4+b969d70b0b
GITASSEMBLYINFORMATIONALVERSION: 1.7.4-foo-bar.4+b969d70b0b
GITBUILDVERSION: 1.7.4.27065
GITBUILDVERSIONSIMPLE: 1.7.4
NBGV_ASSEMBLYFILEVERSION: 1.7.4.27065
NBGV_ASSEMBLYINFORMATIONALVERSION: 1.7.4-foo-bar.4+b969d70b0b
NBGV_ASSEMBLYVERSION: 1.7.0.0
NBGV_BUILDMETADATAFRAGMENT: +b969d70b0b
NBGV_BUILDNUMBER: 4
NBGV_CLOUDBUILDNUMBER: 1.7.4-foo-bar.4+b969d70b0b
NBGV_GITCOMMITID: b969d70b0b7e33ea68ae19e42a8a6457d14e2306
NBGV_GITCOMMITIDSHORT: b969d70b0b
NBGV_MAJORMINORVERSION: 1.7
NBGV_NPMPACKAGEVERSION: 1.7.4-foo-bar.4.b969d70b0b
NBGV_NUGETPACKAGEVERSION: 1.7.4-foo-bar.4.b969d70b0b
NBGV_PRERELEASEVERSION: -foo-bar.4
NBGV_PRERELEASEVERSIONNOLEADINGHYPHEN: foo-bar.4
NBGV_PUBLICRELEASE: False
NBGV_SEMVER1: 1.7.4-foo-bar-0004b969d70b0b
NBGV_SEMVER1NUMERICIDENTIFIERPADDING: 4
NBGV_SEMVER2: 1.7.4-foo-bar.4.b969d70b0b
NBGV_SIMPLEVERSION: 1.7.4
NBGV_VERSION: 1.7.4.27065
NBGV_VERSIONFILEFOUND: True
NBGV_VERSIONHEIGHT: 4
NBGV_VERSIONHEIGHTOFFSET: 0
NBGV_VERSIONMAJOR: 1
NBGV_VERSIONMINOR: 7
NBGV_VERSIONREVISION: 27065
```

And here are the relevant details from `dotnet pack`. Note I am explicitly passing `NBGV_NUGETPACKAGEVERSION` as `/p:PackageVersion`. See the attachment for the complete log.

```
[command]C:\hostedtoolcache\windows\dncs\2.2.300\x64\dotnet.exe pack d:\a\1\s\src\TestLibrary\TestLibrary.csproj --configuration Release --output d:\a\1\a/nuget --no-build --include-symbols --include-source --verbosity Detailed /p:PackageVersion=1.7.4-foo-bar.4.b969d70b0b

Task "PackTask"
 Successfully created package 'd:\a\1\a/nuget\TestLibrary.1.7.4-foo-bar.4.gb969d70b0b.nupkg'.
```

Note the version being passed to the command doesn't match the version that is being produced, nor does the output match any of the environment variables.

```
INPUT:   1.7.4-foo-bar.4.b969d70b0b
OUTPUT:  1.7.4-foo-bar.4.gb969d70b0b
```

There appears to be 2 different issues here:

1. NB.GV is overriding the passed in `/p:PackageVersion`. The normal behavior of MSBuild is that passed in parameters override what is in the build. Note that the same problem seems to exist with `/p:InformationalVersion`, `/p:FileVersion` and `/p:AssemblyVersion` which cannot be overridden explicitly when the `Nerdbank.GitVersioning` package is referenced.
2. NB.GV is producing the wrong version in this case. There are no environment variables that match the version of package that is being produced, so it cannot be referred to later in the build script.

[log_environment_variables.zip](https://github.com/AArnott/Nerdbank.GitVersioning/files/3348911/log_environment_variables.zip)
[log_dotnet_build.zip](https://github.com/AArnott/Nerdbank.GitVersioning/files/3348912/log_dotnet_build.zip)
[log_dotnet_pack.zip](https://github.com/AArnott/Nerdbank.GitVersioning/files/3348910/log_dotnet_pack.zip)

----------------------------------------------
`Nerdbank.GitVersioning` version: 2.3.183
`nbgv` version: 2.3.1 (which produces the environment variables)

```
- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install nbgv --tool-path . --add-source https://api.nuget.org/v3/index.json --version 2.3.1
  displayName: Install NBGV tool (GitVersioning)

- script: nbgv cloud --common-vars --all-vars
  displayName: 'Set Version'
```

**Comment by AArnott** [comment] 2019-07-02 13:04
Global properties (those set with the `/p:` switch)  *cannot* be "overridden". MSBuild doesn't allow it. I think the problem here is that you're setting the wrong property. The one that `dotnet pack` cares about isn't `PackageVersion` but just `Version` IIRC. You can see the NB.GV targets set that property here:

https://github.com/AArnott/Nerdbank.GitVersioning/blob/9880338a605b64e8750208883053b4362b7216be/src/Nerdbank.GitVersioning.Tasks/build/Nerdbank.GitVersioning.targets#L91

So if you use `/p:Version=xxx` instead I think you'll find the package ends up with the version you set.

Now, if you ignore the `/p:` switch entirely for the moment (since you're setting the wrong one), the reason you're seeing different results between environment variables and the build (specifically the extra `g`) is mostly likely because the version of the `nbgv` tool that you're using (if that's what's setting the environment variables) and the version on the Nerdbank.GitVersioning package reference are not the same, so they have different behaviors.

NB.GV went through something of a growing pain recently. Several folks wanted the `g` removed, so we removed it. But then we started finding out / remembering why it was there in the first place: *some* git commit IDs (or at least their first 10 characters) are made up entirely of digits, and have leading zeros. This makes an entire "identifier" in semver2 a "number" and numbers are forbidden to contain leading zeros. So in fact we have to stick a letter in there somewhere, and a leading `g` (for "git") is the standard we've used for a long time so we went back to it. We add the `g` unconditionally (i.e. in more than just the absolutely required all-digit cases) so that the behavior is consistent and people don't get thrown off and cause automation failures when the `g` is only rarely inserted.

**Comment by AArnott** [comment] 2019-07-02 13:05
I hope this helps. I'll close the issue for now optimistic that my response addresses your concerns. But feel free to respond if you have any remaining.

**Closed by AArnott** 2019-07-02 13:05 UTC

**Comment by NightOwl888** [comment] 2019-07-02 13:46
Frankly, I don't care whether the `g` is there or not. But I do need a way to reference the package version later in the script so I can promote the package to the right view, and that is what the issue is here. There are no environment variables that contain that exact version number. The only way I have to get it is from the package file itself.

Also, [PackageVersion](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#packageversion) is the MSBuild property to use according to the official docs. It defaults to the value of `Version`, but so do a lot of the other version properties, which is why I avoid it.

For the time being, I have "fixed" both issues by conditionally removing the `Nerdbank.GitVersioning` package when building on the server. But as you mentioned, without the `g` there will be problems so it really isn't a good fix.

**Comment by NightOwl888** [comment] 2019-07-02 14:04
> Global properties (those set with the /p: switch) cannot be "overridden". MSBuild doesn't allow it.

BTW - without `Nerdbank.GitVersioning` in place, the properties can be overridden just fine by passing them in. So clearly this is something MSBuild allows but Nerdbank.GitVersioning does not. But  [Nerdbank.GitVersioning is not using the correct MSBuild properties](https://github.com/AArnott/Nerdbank.GitVersioning/blob/9880338a605b64e8750208883053b4362b7216be/src/Nerdbank.GitVersioning.Tasks/build/Nerdbank.GitVersioning.targets#L147-L148) for the new `.csproj` format. Again they are:

1. PackageVersion
2. AssemblyVersion
3. FileVersion
4. InformationalVersion

If these names are specified (again, see the [official docs](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#properties-per-attribute)), then you can pass in all 4 version numbers and it works perfectly.

**Comment by AArnott** [comment] 2019-07-02 15:37
Interesting. I can see that the PackTask itself does indeed take a PackageVersion property. So how that's being ignored or ... hmm... maybe during msbuild *execution* a global property *can* be overridden. I know it can't be during evaluation, but during execution I'm not sure. Maybe that's how NB.GV is overwriting the PackageVersion when you set it with `/p:`.

And ya, I can see how you'd want the versions to align. Can you confirm that you're using the `nbgv` tool? And given it's important to you for its output to match what the NB.GV package to produce during the build, have you "pinned" both versions so that they always match?

**Comment by AArnott** [comment] 2019-07-02 15:39
> but Nerdbank.GitVersioning does not. But Nerdbank.GitVersioning is not using the correct MSBuild properties

NB.GV doesn't consume those. NB.GV is older than those properties, which are all fairly new. And the whole point of NB.GV is to "own" the version and generate it based on git data, so it's not a supported scenario to consume NB.GV but also set version properties yourself. There are published supported ways to influence how NB.GV does this (e.g. the version.json file), but NB.GV doesn't for example take steps to avoid setting properties that have already been set.

**Comment by NightOwl888** [comment] 2019-07-02 17:47
> And ya, I can see how you'd want the versions to align. Can you confirm that you're using the nbgv tool? And given it's important to you for its output to match what the NB.GV package to produce during the build, have you "pinned" both versions so that they always match?

I am using the following versions:

Nerdbank.GitVersioning version: 2.3.183
nbgv version: 2.3.1 (which produces the environment variables)

And yes, I have pinned both to that exact version to prevent version drift.

**Comment by AArnott** [comment] 2019-07-02 18:01
OK, so you've pinned them, but they clearly *don't* match since one is 2.3.1 and one is 2.3.183. Make them match (using the latest one is better 😄 ) and you should be in good shape.

**Comment by NightOwl888** [comment] 2019-07-02 18:45
Thanks. I thought I was using the latest of both :(.

But pinning them both to the latest stable `2.3.183` yields the same result.

```
NBGV_ASSEMBLYFILEVERSION: 1.7.10.14074
NBGV_ASSEMBLYINFORMATIONALVERSION: 1.7.10-foo-bar.10+fa36fa2538
NBGV_ASSEMBLYVERSION: 1.0.0.0
NBGV_BUILDMETADATAFRAGMENT: +fa36fa2538
NBGV_BUILDNUMBER: 10
NBGV_CLOUDBUILDNUMBER: 1.7.10-foo-bar.10+fa36fa2538
NBGV_GITCOMMITID: fa36fa2538c11ce67c4da8559010c86ea63b42d7
NBGV_GITCOMMITIDSHORT: fa36fa2538
NBGV_MAJORMINORVERSION: 1.7
NBGV_NPMPACKAGEVERSION: 1.7.10-foo-bar.10.fa36fa2538
NBGV_NUGETPACKAGEVERSION: 1.7.10-foo-bar.10.fa36fa2538
NBGV_PRERELEASEVERSION: -foo-bar.10
NBGV_PRERELEASEVERSIONNOLEADINGHYPHEN: foo-bar.10
NBGV_PUBLICRELEASE: False
NBGV_SEMVER1: 1.7.10-foo-bar-0010fa36fa2538
NBGV_SEMVER1NUMERICIDENTIFIERPADDING: 4
NBGV_SEMVER2: 1.7.10-foo-bar.10.fa36fa2538
NBGV_SIMPLEVERSION: 1.7.10
NBGV_VERSION: 1.7.10.14074
NBGV_VERSIONFILEFOUND: True
NBGV_VERSIONHEIGHT: 10
NBGV_VERSIONHEIGHTOFFSET: 0
NBGV_VERSIONMAJOR: 1
NBGV_VERSIONMINOR: 7
NBGV_VERSIONREVISION: 14074
```

![image](https://user-images.githubusercontent.com/1538288/60538038-ff157500-9d33-11e9-8162-cd60e3761f71.png)

**Comment by AArnott** [comment] 2019-07-02 19:08
This seems odd that nbgv would produce a `NuGetPackageVersion` without a `g` but NB.GV (which uses the same `VersionOracle` class would add the `g` prefix if they are both the same version. 
If you can share a git repo that reproduces this I can investigate.

**Comment by NightOwl888** [comment] 2019-07-02 19:39
It turns out, I updated the `nbgv` version in a template in a separate repo and pushed the commit, but I forgot to tag it and pin the `azure-pipelines.yml` file to the new version of the template. After getting the versioning straightened out the `g` now appears in the number.

I still think it is a pretty serious limitation of NB.GV that MSBuild parameters for versions cannot be passed in using the documented properties, though.
