### ISSUE TITLE
Project dependencies do not have the correct version number when packaged

### ISSUE THREAD

**Issue by camp-007** [AArnott/Nerdbank.GitVersioning#144] opened 2017-07-21 04:40 UTC
I have a .net standard class library project named "ClassLibrary1" defined as:

````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="1.6.35" PrivateAssets="All" />
  </ItemGroup>

</Project>
````
This project uses a version.json file defined as:

````
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "2.1"
}
````
I have a second class library project "ClassLibrary2" which depends on the first:
````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
    <PackageReference Include="Nerdbank.GitVersioning" Version="1.6.35" PrivateAssets="All" />
  </ItemGroup>

</Project>
````
This project uses a version.json defined as:
````
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "3.5"
}
````
Building and packing either project results in a nuget package that is properly versioned based on the respective version.json file.  However, the nuget package for ClassLibrary2 has a dependency on ClassLibrary1 >= 1.0.0.  I would expect the dependency to require ClassLibrary1 >= 2.1.0.

If I'm not using NerdBank.Versioning, and instead have explicity <Version> tags in the .csproj files, then I get the expected behavior (ClassLibrary2's nuget package declares a dependency on ClassLibrary1 >= 2.1.0)

Am I doing something wrong?  Or are my expectations incorrect?

Thanks in advance for any help.

**Comment by AArnott** [comment] 2017-07-21 05:38
Dupe of #113. See there for links to the NuGet/.NET SDK bugs and a workaround.

**Closed by AArnott** 2017-07-21 05:38 UTC

**Comment by camp-007** [comment] 2017-07-21 18:41
My apologies.  I even looked at the open issues first, but I guess I need practice reading.  Thank you for your response (and patience)!

**Comment by AArnott** [comment] 2017-07-21 19:43
No problem. Thanks for doing due diligence first. I miss dupes myself on other people's projects too.
