### ISSUE TITLE
Unexpected characters at the end of generated .Version.cs file

### ISSUE THREAD

**Issue by IlyaBiryukov** [AArnott/Nerdbank.GitVersioning#52] opened 2016-02-05 21:30 UTC
We use Nerdbank.GitVersioning v 1.2.8. NuGet package, and while building our net46 project in VS 2015, there are some unexpected characters at the end of the generated *.Version.cs file, and the build fails with 
Error CS1022 Type or namespace definition, or end-of-file expected ....Version.cs (28).

Here is the generated file with some fields in ThisAssembly class reduced to "..." for brevity, note the extra } at the end.

```C#
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersionAttribute("0.1.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.1.150.919")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.1.150-alpha+g970364a3df")]


internal sealed partial class ThisAssembly {
    internal const string AssemblyVersion = "0.1.0.0";
    internal const string AssemblyFileVersion = "0.1.150.919";
    internal const string AssemblyInformationalVersion = "0.1.150-alpha+g970364a3df";
    internal const string AssemblyName = "...";
    internal const string PublicKey = @"...";
    internal const string PublicKeyToken = "...";
    internal const string RootNamespace = "...";
    private ThisAssembly() {
    }
}

}

```

**Comment by AArnott** [comment] 2016-02-06 03:43
Duplicate of #50. Please upgrade to latest version which already has the fix.

**Closed by AArnott** 2016-02-06 03:43 UTC
