### ISSUE TITLE
Docs: CloudBuild: Include all variables

### ISSUE THREAD

**Issue by onovotny** [AArnott/Nerdbank.GitVersioning#178] opened 2018-05-18 18:01 UTC
Today, the cloudbuild, set variables option sets three variables. Would it make sense to set all of them and not just those three? There's various reasons they could be useful and it'd reduce the need to call the PowerShell version directly if everything was set as an env variable.

**Comment by AArnott** [comment] 2018-05-18 18:39
Isn't this a dupe of #130 which is already fixed?

**Comment by onovotny** [comment] 2018-05-18 18:42
You're right. I missed it because it's not documented here:
https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/doc/cloudbuild.md

`setAllVariables`

**Comment by AArnott** [comment] 2018-05-18 18:45
Care to review #179, @onovotny?

**Closed** 2018-05-18 18:54 UTC
